version: '3.7'
services:

  mongo-db:
    image: 'mongo:4.4'
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_DATABASE}'
    volumes:
      - './db-data:/data/db'

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${DB_USERNAME}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${DB_PASSWORD}'
      ME_CONFIG_MONGODB_SERVER: mongo-db

  soap-server:
    build: './php/'
    container_name: soap-server
    environment:
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DATABASE: '${DB_DATABASE}'
    ports :
      - "9000"
    volumes:
      - './soap-server:/var/www/html/'
    depends_on:
      - mongo-db

  nginx:
    build:
      context: ./nginx/
      args:
        - FILE_NAME=nginx-1.conf
    container_name: nginx-1
    ports:
      - "4001:80"
    volumes:
      - './soap-server:/var/www/html/'
    depends_on:
      - mongo-db

volumes:
  db-data:
